name: C/C++ CI

on:
  push:
    paths:
    - "data/userData.json"
    deleted: false

jobs:
  buildRun:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: update
      run: python3 data/checkUpdate.py
    - name: commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with: 
        commit_message: 自动拉取图鉴网数据
        file_pattern: "data/data.min.json"
        skip_dirty_check: false
    - name: build
      run: mkdir build && cd ./build && ls -aR && cmake ../ && make
    - name: run
      run: cd ./build && ./bcjh -s && ./bcjh -s 
      run: echo "已生成两个方案~"

